title: NTUPC
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://pufanyi.github.io/NTUPC/

aux_links:
  NTU: https://www.ntu.edu.sg/
  ICPC: https://icpc.global/
